### ISSUE TITLE
Node gradle plugin

### ISSUE THREAD

**Issue by Frontrider** [i-net-software/JWebAssembly#11]
Where are you getting the node Gradle plugin from? Currently, there are no jars in the repositories, so I can't take a look at the project.

**Comment by Horcrux7** [comment]
I am unclear if I have understand your question.
The node plugin in the build script come from the gradle plugin repository.
https://plugins.gradle.org/plugin/com.moowork.node

**Comment by Frontrider** [comment]
You understand it correctly. I looked up the repo and there was only a pom file and hashes. The jar was not there.

**Comment by Horcrux7** [comment]
I have never try to download a gradle plugin. I have no idea on which position the binary are located. I run simple the gradle script with declared plugin. The gradle runtime download the plugin if not in the cache.

That I am unclear what your real problem is.

**Comment by Frontrider** [comment]
Do not clear your caches then. If you do, you'll lose the plugin. Gradle is the thing that can no longer download it.

**Comment by Horcrux7** [comment]
Now I understand your problem. I will check this the next days. Currently I am on road.

**Comment by Horcrux7** [comment]
I have restart the build job on travis and it works. https://travis-ci.org/i-net-software/JWebAssembly

I have delete all files with "moowork" from my Gradle cache and run the build locally and it works. The files were back in the cache.

Which error do you receive? Do you behind a firewall/proxy?
