### ISSUE TITLE
Unable to run Hello World sample

### ISSUE THREAD

**Issue by harshrathod50** [i-net-software/JWebAssembly#13]
The _Hello World_ sample compiles successfully in my "java_wa" maven project using NetBeans but an exception occurs while executing it. Do I need to include any more dependencies? I'm using Java 13. Is it okay?

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: 'java.lang.Object de.inetsoftware.jwebassembly.web.JSObject.win_get(java.lang.String)'
	at de.inetsoftware.jwebassembly.web.JSObject.win_get(Native Method)
	at de.inetsoftware.jwebassembly.web.dom.Window.document(Window.java:43)
	at com.mycompany.java_wa.HelloWorld.main(HelloWorld.java:21)
```

**Comment by Horcrux7** [comment]
How did you try to run it? It look like that you want to run it as a poor Java program. This will not work.

You can run the compiled *.wasm file in a browser or you run it with the [emulator](https://github.com/i-net-software/JWebAssembly/wiki/Debugging).

**Comment by harshrathod50** [comment]
I'm new to this. I simply created a maven project in NetBeans. Tweaked pom.xml like this:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.mycompany</groupId>
    <artifactId>java_wa</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>13</maven.compiler.source>
        <maven.compiler.target>13</maven.compiler.target>
    </properties>
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
    <dependencies>
        <dependency>
            <groupId>com.github.i-net-software</groupId>
            <artifactId>jwebassembly-api</artifactId>
            <version>master-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>
```

The project compiled but didn't execute.

**Comment by Horcrux7** [comment]
I am not familiar with Maven build scripts. But I think this compile the Java sources only to a *.jar file. But what you need is to compile it to a *.wasm file.

Currently there is no Maven plugin to do this and never is working on it. There is currently only a Gradle plugin. It will be nice if you want write a Maven plugin.

To compile to a *.wasm file you need to call the API of the class [JWebAssembly](https://github.com/i-net-software/JWebAssembly/blob/master/src/de/inetsoftware/jwebassembly/JWebAssembly.java).

Can you call Java API in Maven directly? Gradle can do it.

**Comment by harshrathod50** [comment]
Okay, now that explains why I didn't get any *.wasm file.

**Comment by Horcrux7** [comment]
Do you have solve the problem? Can I close this ticket?

**Comment by harshrathod50** [comment]
I'm done! Thanks.
