### ISSUE TITLE
Hello World example live is not running 

### ISSUE THREAD

**Issue by atlasTest2019** [i-net-software/JWebAssembly#21]
I just tried to test your Hello World example on windows but could not get it running:

with chrome Version 87.0.4280.88 (64-Bit):

1. running default chrome chrashed with - CompileError: WebAssembly.instantiateStreaming(): invalid value type 'externref', enable with --experimental-wasm-reftypes @+16
2. running chrome with the flags in your documentation chrashed with - same error
3. enabling "Experimental WebAssembly" in chrome flags chrashed with CompileError: WebAssembly.instantiateStreaming(): Compiling function #26:"de/inetsoftware/jwebassembly/web/dom/Document.body" failed: Invalid indexed heap type, enable with --experimental-wasm-typed-funcref @+1548
4. running chrome with the flag --js-flags="--experimental-wasm-typed-funcref" chrashed with CompileError: WebAssembly.instantiateStreaming(): Compiling function #26:"de/inetsoftware/jwebassembly/web/dom/Document.body" failed: expected 0 elements on the stack for fallthru to @26, found 1 @+1549

with firefox nightly 85.0a1 (2020-12-07) (64-Bit):

1. CompileError: wasm validation error: at offset 1548: invalid heap type

with Edge Version 87.0.664.47 (64-Bit):

1. CompileError: WebAssembly.instantiateStreaming(): invalid value type 'externref', enable with --experimental-wasm-reftypes @+16

**Comment by Horcrux7** [comment]
There are frequently changes on the needed experimental ref and GC features currently. If it more stable I will fix it.

**Comment by atlasTest2019** [comment]
thanks for the immediate response.
I tried to build your HelloWorld example with access to the HTML via JS locally but could not run it either.
Is there maybe an old version of the compiler that still runs successfully or is the API completely broken now ?

**Comment by Horcrux7** [comment]
You need a browser from the sample age. So 9-12 month old browser.

After month of heavy development it look like that the browser API become stable now. It is time that I fix this in the next weeks.

**Comment by Horcrux7** [comment]
I have test the sample with Firefox nightly and with Chrome and the corrected command line switches. Bothe work for me currently.

**Comment by Horcrux7** [comment]
Also with Edge and the same flags from Chrome it is working. Both use the same source base. This was expected.
