### ISSUE TITLE
[Question] Deno support

### ISSUE THREAD

**Issue by CC007** [i-net-software/JWebAssembly#22]
I saw that deno has the ability to run wasm files (https://dev.to/taterbase/running-a-go-program-in-deno-via-wasm-2l08) and through its plugin interface can provide a Webview that allows you to open a window on the desktop (see https://youtu.be/428ejtNbd5A?t=942).

Do the dom operations that JWebAssembly provide also work with such windows? How would one go about doing this?

**Comment by Horcrux7** [comment]
I does not know what can do this deno. Here you find a feature test: https://wasm-feature-detect.surma.technology/

Supports it referenceTypes? Then it can work. 

But JWebAssembly is not production ready now.
