### ISSUE TITLE
Can't Compile to WASM

### ISSUE THREAD

**Issue by fribeiro1** [i-net-software/JWebAssembly#28]
I am getting [an error](https://gist.github.com/fribeiro1/8aca965604ae633e4d16e45ca550d16e) when compiling [the Java HelloWorld application](https://gist.github.com/fribeiro1/fac4e0d4765efbfab284cc693157211d) to WASM.

I am using JWebAssembly 0.3, OpenJDK 17, and Ubuntu 20.04.

**Comment by FriwiDev** [comment]
Are you sure you provided the right file? It doesn't seem to be called "WasmSample.java"

**Comment by fribeiro1** [comment]
Fixed.

**Comment by Horcrux7** [comment]
> de.inetsoftware.jwebassembly.WasmException: Abstract or native method can not be used: java/lang/Thread.currentThread()Ljava/lang/Thread;

Native methods of Java must be replaces with own implementations. For example you can use https://github.com/i-net-software/JWebAssembly-API

**Comment by fribeiro1** [comment]
Got it. Thanks.
