### ISSUE TITLE
Setting up the JWebAssembly API 

### ISSUE THREAD

**Issue by Deepansharora27** [i-net-software/JWebAssembly#36]
Hi, 

I was trying to set up the JWebAssembly on my IntelliJ Idea Community Edition IDE. 

I followed the Documentation, and I have done the pre-requisite step of adding the JWebAssembly API library to my Java Project in the IDE.
After adding the API to the Project, I am able to build the Project Successfully, however, the point where I am stuck is that I have created my Class File(I used the Canonical Hello World Example which is being used in the Documentation) and I have saved it at the root. Now Hypothetically I am assuming that after Building the file, I should get the generated WebAssembly Binary however it is not the case. 

I just want to ask Is it the correct way of setting up the API or am I doing something wrong here?

**Comment by Horcrux7** [comment]
Did you run the Gradle task "wasm"? Running the "wasm" task produces the WebAssembly output.

PS: I am not familiar with IntelliJ Idea. If you have any suggestions for better integration, please tell me.

**Comment by Deepansharora27** [comment]
I guess I haven't because I have only followed the steps as of now which are mentioned in the initial references of the documentation. 

Well I am not having any ideas for better intergation as of now but once I am done setting up the workflow with the API, I want to write a detailed Blogost on this because as of now over the Internet, I do not see any referencing blogpost/article iterating through the workflow for using JWebAssembly API and how can we generate a binary and deploy it as per our use case. 
This in turn will attract developers to the project and many people will get to know about this 😊

How does that sound ?

**Comment by Deepansharora27** [comment]
@Horcrux7 
> I guess I haven't because I have only followed the steps as of now which are mentioned in the initial references of the documentation.
> 
> Well I am not having any ideas for better intergation as of now but once I am done setting up the workflow with the API, I want to write a detailed Blogost on this because as of now over the Internet, I do not see any referencing blogpost/article iterating through the workflow for using JWebAssembly API and how can we generate a binary and deploy it as per our use case. This in turn will attract developers to the project and many people will get to know about this 😊
> 
> How does that sound ?

**Comment by Horcrux7** [comment]
I think I see where the problem was in the documentation. I have improve the point. Writing clear documentation is difficult. Any hint is welcome.

> Well I am not having any ideas for better intergation as of now but once I am done setting up the workflow with the API, I want to write a detailed Blogost on this because as of now over the Internet, I do not see any referencing blogpost/article iterating through the workflow for using JWebAssembly API and how can we generate a binary and deploy it as per our use case. This in turn will attract developers to the project and many people will get to know about this 😊
> 
> How does that sound ?

More developers sounds ever good.

**Comment by Deepansharora27** [comment]
> I think I see where the problem was in the documentation. I have improve the point. Writing clear documentation is difficult. Any hint is welcome.
> 
> > Well I am not having any ideas for better intergation as of now but once I am done setting up the workflow with the API, I want to write a detailed Blogost on this because as of now over the Internet, I do not see any referencing blogpost/article iterating through the workflow for using JWebAssembly API and how can we generate a binary and deploy it as per our use case. This in turn will attract developers to the project and many people will get to know about this 😊
> > How does that sound ?
> 
> More developers sounds ever good.

We will improve this. No Worries 😊

Can you educate me about, how can I include and run the gradle task Wasm ?

**Comment by Horcrux7** [comment]
Do you have read: https://github.com/i-net-software/JWebAssembly/wiki/Build-with-Gradle

**Comment by Deepansharora27** [comment]
Aah I just stumbled across the `wasm-task` property just now. Let me integrate it into my Project.

**Comment by Deepansharora27** [comment]
@Horcrux7 I just tried out by integrating the wasm-task property into the Gradle File, but still I am not able to generate the Binary with it.

**Comment by Deepansharora27** [comment]
> @Horcrux7 I just tried out by integrating the wasm-task property into the Gradle File, but still I am not able to generate the Binary with it. The Build Process is succeeding but still the binary is not present in the root.

**Comment by Deepansharora27** [comment]
> > The Build Process is succeeding but still the binary is not present in the root.
> 
> What you means with the root? By default Gradle saved it in `build/distributions` if you does not set a `destinationDir`.

By root I mean root of the Project. Yes I haven't set a `destinationDir`

**Comment by Horcrux7** [comment]
Do you have an output in `build/distributions`?

**Comment by Deepansharora27** [comment]
> Do you have an output in `build/distributions`?

No I don't

**Comment by Horcrux7** [comment]
Ok, I don't know what your problem is:

* Have the other task produce any files. For example `compileJava`
* What you see in the Gradle console?
* enable the debug log level to see more details

**Comment by Deepansharora27** [comment]
Hi @Horcrux7, 

I dug deep into the Workflow and I am facing the following issues:

This is the `build.gradle` file that I am using:

```
apply plugin: 'java'

buildscript {
    repositories {
        maven { url uri('https://jitpack.io') }
    }
    dependencies {
        classpath 'com.github.i-net-software:jwebassembly-gradle:master-SNAPSHOT'
    }
}

apply plugin: 'de.inetsoftware.jwebassembly'

repositories {
    maven { url 'https://jitpack.io' }
}
dependencies {
    implementation 'com.github.i-net-software:jwebassembly-api:master-SNAPSHOT'
}

sourceSets {
    main {
        java {
            srcDir 'src/main/java'
        }
    }
}


wasm {
    //Get more debug information if there are problems.
    //logging.level = LogLevel.DEBUG
    //logging.levelInternal = LogLevel.DEBUG

    //Change the output format to the text format *.wat.
    //This can be helpful to understand the problems if you see the generated code as text format.
    //format = 'text'

    //The used JWebAssembly compiler version. The default is the latest release '+'.
    //You can set any valid Gradle version string or a full dependency string.
    //The snapshot version is recommended until a stable release.
    //compilerVersion = 0.2
    compilerVersion = 'com.github.i-net-software:jwebassembly:master-SNAPSHOT'

    //Write method and parameter names into the output *.wasm file.
    //The file will be approximate 10% larger. And it generate a source map.
    //With a source map you can see in the debugger of the browser your source code if available.
    debugNames = true

    //Set an absolute or relative path between the final wasm file location and the source files location.
    ///This is needed for debugging in the browser. It work only if debugNames = true.
    //sourceMapBase = '../../src/main/java/'
    //sourceMapBase = '/src/main/java/'

    //set the destination dir
    //destinationDir = file( 'targetDir' )
}

```

With this Gradle File, the build is succeeding however if I hop onto my Class file in `/src/main/java` directory, I am getting the following error:


![Screenshot 2022-05-11 at 9 47 41 PM](https://user-images.githubusercontent.com/43300955/167898487-14eeb7de-2a27-42e4-aaca-c252b7a143b5.png)


What Should I do in this case ?

**Comment by Deepansharora27** [comment]
Also, attaching the Build Output for reference:

![Uploading Screenshot 2022-05-11 at 9.51.34 PM.png…]()

**Comment by Deepansharora27** [comment]
> Hi @Horcrux7,
> 
> I dug deep into the Workflow and I am facing the following issues:
> 
> This is the `build.gradle` file that I am using:
> 
> ```
> apply plugin: 'java'
> 
> buildscript {
>     repositories {
>         maven { url uri('https://jitpack.io') }
>     }
>     dependencies {
>         classpath 'com.github.i-net-software:jwebassembly-gradle:master-SNAPSHOT'
>     }
> }
> 
> apply plugin: 'de.inetsoftware.jwebassembly'
> 
> repositories {
>     maven { url 'https://jitpack.io' }
> }
> dependencies {
>     implementation 'com.github.i-net-software:jwebassembly-api:master-SNAPSHOT'
> }
> 
> sourceSets {
>     main {
>         java {
>             srcDir 'src/main/java'
>         }
>     }
> }
> 
> 
> wasm {
>     //Get more debug information if there are problems.
>     //logging.level = LogLevel.DEBUG
>     //logging.levelInternal = LogLevel.DEBUG
> 
>     //Change the output format to the text format *.wat.
>     //This can be helpful to understand the problems if you see the generated code as text format.
>     //format = 'text'
> 
>     //The used JWebAssembly compiler version. The default is the latest release '+'.
>     //You can set any valid Gradle version string or a full dependency string.
>     //The snapshot version is recommended until a stable release.
>     //compilerVersion = 0.2
>     compilerVersion = 'com.github.i-net-software:jwebassembly:master-SNAPSHOT'
> 
>     //Write method and parameter names into the output *.wasm file.
>     //The file will be approximate 10% larger. And it generate a source map.
>     //With a source map you can see in the debugger of the browser your source code if available.
>     debugNames = true
> 
>     //Set an absolute or relative path between the final wasm file location and the source files location.
>     ///This is needed for debugging in the browser. It work only if debugNames = true.
>     //sourceMapBase = '../../src/main/java/'
>     //sourceMapBase = '/src/main/java/'
> 
>     //set the destination dir
>     //destinationDir = file( 'targetDir' )
> }
> ```
> 
> With this Gradle File, the build is succeeding however if I hop onto my Class file in `/src/main/java` directory, I am getting the following error:
> 
> ![Screenshot 2022-05-11 at 9 47 41 PM](https://user-images.githubusercontent.com/43300955/167898487-14eeb7de-2a27-42e4-aaca-c252b7a143b5.png)
> 
> What Should I do in this case ?

& How Should I resolve this error that I am facing, it's showing to me that `de` as a symbol is not defined and also `Export` is not defined in the Source Code even though the Build is succeeding.

**Comment by Horcrux7** [comment]
It look like that you not have add jwebassembly-api dependency to your project. This is the first step: https://github.com/i-net-software/JWebAssembly/wiki/Getting-Started
