### ISSUE TITLE
Compiling without Gradle

### ISSUE THREAD

**Issue by DevTaube** [i-net-software/JWebAssembly#38]
Looking at the repository, I only found information about compiling using Gradle. Sadly I don't use Gradle (except in Android Studio) and wondered how I could compile from cmd or from inside Java code (maybe I could call the methods that Gradle calls somehow?). How would I go about doing this?

Thx

**Comment by Horcrux7** [comment]
Which build system do you want use instead?

You must also set a library. Only in your sources and in the added libraries the JWebAssembly compiler search for classes with annotations.

**Comment by DevTaube** [comment]
> Which build system do you want use instead?

I didn't want to use any build system...

> You must also set a library. Only in your sources and in the added libraries the JWebAssembly compiler search for classes with annotations.

Oh! Thats probably explains why I have problems with importing and exporting methods... I'l have a look into that later, thanks!
