### ISSUE TITLE
Outdated

### ISSUE THREAD

**Issue by Eskerepvp** [i-net-software/JWebAssembly#39]
compile, runtime, testCompile, and testRuntime configurations introduced by the Java plugin have been deprecated since [Gradle 4.10](https://docs.gradle.org/4.10/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) ([Aug 27, 2018](https://gradle.org/releases/)), and were finally removed in [Gradle 7.0](https://docs.gradle.org/7.0/userguide/java_library_plugin.html#sec:java_library_configurations_graph) ([Apr 9, 2021](https://gradle.org/releases/)).

**Comment by Horcrux7** [comment]
This can be right. But which problem do you see with JWebAssembly? Is some documentation wrong?

**Comment by Eskerepvp** [comment]
yes I spent all night trying to configure jwebassembly with gradle, but couldn't because the documentation for building with gradle is wrong. I still haven't figured it out. Documentation/Example Project with current gradle would be helpful...

**Comment by Horcrux7** [comment]
I change "compile" to "implementation". This is the only needed change that I can see.

**Comment by Eskerepvp** [comment]
i've tried that, i wouldn't of stayed up all night unsuccessfully trying to figure it out if it was that simple

**Comment by Horcrux7** [comment]
Please write a little more details. What you try? What show the Gradle console? Which files are created? Do you receive any error messages? Which?

**Comment by Eskerepvp** [comment]
I made a new issue, also HelloWorld.wasm is generated but the file is near empty 
![image](https://user-images.githubusercontent.com/75771072/170637391-1c82ea4a-5c4f-4ce9-b4ab-95b2622e8ad1.png)

**Comment by Horcrux7** [comment]
I close the ticket because the other issue.

If the *.wasm is very small then you have no method with @Export annotation.
