### ISSUE TITLE
ENHANCMENT

### ISSUE THREAD

**Issue by Eskerepvp** [i-net-software/JWebAssembly#45]
Create a JWebAssembly discord support server? Because communicating over github issues is kinda wack.

**Comment by Horcrux7** [comment]
Why not use the WebAssembly discord server that is linked in the support page: https://github.com/i-net-software/JWebAssembly/wiki/Support

**Comment by Eskerepvp** [comment]
Because they don't have any channels for JWebAssembly (they don't even know this project  exists) And having a support discord server would make trouble shooting alot easier and make more people want to use this. And your not even in the web assembly discord server :(

**Comment by Horcrux7** [comment]
Now there is a channel [languages/java](https://discord.com/channels/453584038356058112/982781407791300658)
