### ISSUE TITLE
How to compile Pixelitor to JavaScript?

### ISSUE THREAD

**Issue by 2dpdlja496or43iq** [i-net-software/JWebAssembly#59]
https://github.com/lbalazscs/Pixelitor

**Comment by Horcrux7** [comment]
If you does not want develop software then your are wrong here. JWebAssembly is tool for software development. 

[https://github.com/i-net-software/JWebAssembly/wiki/FAQ](https://github.com/i-net-software/JWebAssembly/wiki/FAQ)
